# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: EUPL-1.2
#
# Image automation for the hsm-worker binary built from
# wallet-r2ps/hsm-worker/Containerfile.
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: rust-hsm-worker
  namespace: flux-system
spec:
  image: zot.registry.svc.cluster.local:5000/diggsweden/rust-hsm-worker
  interval: 1m
  insecure: true
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rust-hsm-worker-test
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rust-hsm-worker
  filterTags:
    pattern: '^test-(?P<ts>\d+)-\w+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rust-hsm-worker-stage
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rust-hsm-worker
  filterTags:
    pattern: '^stage-(?P<ts>\d+)-\w+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rust-hsm-worker-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rust-hsm-worker
  filterTags:
    pattern: '^prod-(?P<ts>\d+)-\w+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
