# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: EUPL-1.2
#
# Image automation for the wallet-bff binary built from
# wallet-r2ps/wallet-bff/Containerfile and pushed to the in-cluster
# zot registry.
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: rust-wallet-bff
  namespace: flux-system
spec:
  image: zot.registry.svc.cluster.local:5000/diggsweden/rust-wallet-bff
  interval: 1m
  insecure: true
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rust-wallet-bff-test
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rust-wallet-bff
  filterTags:
    pattern: '^test-(?P<ts>\d+)-\w+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rust-wallet-bff-stage
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rust-wallet-bff
  filterTags:
    pattern: '^stage-(?P<ts>\d+)-\w+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rust-wallet-bff-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rust-wallet-bff
  filterTags:
    pattern: '^prod-(?P<ts>\d+)-\w+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
