apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry
  namespace: registry
spec:
  parentRefs:
    - name: dev-local
      namespace: default
      sectionName: https
  hostnames:
    - registry.dev.local
  rules:
    - backendRefs:
        - name: registry-zot
          port: 5000
