---
# Domain used for local ingress
dev_domain: dev.local

# k3s Lima VM name (macOS)
lima_vm_name: k3s
lima_config: "{{ playbook_dir }}/../lima-k3s.yaml"

# Tool versions (Linux binary installs)
argocd_version: "2.13.3"
nerdctl_version: "2.0.3"
buildkit_version: "0.17.1"

# ArgoCD
argocd_base_path: "{{ playbook_dir }}/../argocd"

# kubeconfig
kubeconfig_path: "{{ ansible_facts['env']['HOME'] }}/.kube/config"
