apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    # Single replica for local dev
    replicaCount: 1

    admissionController:
      replicas: 1

    backgroundController:
      replicas: 1

    cleanupController:
      replicas: 1

    reportsController:
      replicas: 1
