apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - sealed-secrets.yaml
  - prometheus-community.yaml
  - grafana.yaml
  - strimzi.yaml
  - kafbat.yaml
  - bitnami.yaml
  - jetstack.yaml
  - zot.yaml
  - vector.yaml
  - garage.yaml
  - kyverno.yaml
