apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: ">=7.0.0 <8.0.0"
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: s3
            bucketNames:
              chunks: loki-data
              ruler: loki-data
              admin: loki-data
            s3:
              endpoint: http://garage.garage.svc.cluster.local:3900
              region: garage
              accessKeyId: GK2e8fad0c31d98d5903a8d6cd
              secretAccessKey: 25adc62332d2054d79639ab4e18e8da75d275fdb3d7ec392c12b8171c7745915
              s3ForcePathStyle: true
              insecure: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
            retention_period: 168h
            max_label_names_per_series: 30
          pattern_ingester:
            enabled: true
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 20Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
        lokiCanary:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
