apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.yaml
  - loki.yaml
  - vector.yaml
  - kafka-podmonitors.yaml
  - kafka-servicemonitor.yaml
  - grafana-dashboards.yaml
  - grafana-route.yaml
  - grafana-admin-external-secret.yaml
