apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
  namespace: registry
spec:
  interval: 30m
  chart:
    spec:
      chart: zot
      sourceRef:
        kind: HelmRepository
        name: zot
        namespace: flux-system
  values:
    persistence: true
    pvc:
      create: true
      storage: 20Gi

    service:
      nodePort: 30500

    mountConfig: true

    configFiles:
      config.json: |-
        {
          "storage": { "rootDirectory": "/var/lib/registry" },
          "http": {
            "address": "0.0.0.0",
            "port": "5000",
            "compat": ["docker2s2"]
          },
          "log": { "level": "info" },
          "extensions": {
            "search": { "enable": true },
            "ui":     { "enable": true }
          }
        }
